# Generated by Django 4.0.4 on 2022-05-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_enrolments_enrolment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('start_dttm', models.DateTimeField()),
                ('end_dttm', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='end_dttm',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='start_dttm',
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
    ]
