# Generated by Django 4.0.4 on 2022-05-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_student_remove_usermembership_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stupass',
            new_name='stusubject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuemail',
        ),
    ]
