# Generated by Django 4.0.4 on 2022-05-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_rename_stupass_student_stusubject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuids',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stuname',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stusubject',
            new_name='subject',
        ),
    ]
